### ISSUE TITLE
Github credentials required but not documented

### ISSUE THREAD

**Issue by mike182uk** [gitevents/core#124]
When running `npm run dev` on a fresh fork of the project im getting:

```
module.js:328
    throw err;
    ^

Error: Cannot find module './github.credentials'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/mike/Projects/OS/gitevents/core/common/development.js:3:14)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
[nodemon] app crashed - waiting for file changes before starting...
```

It looks like a credentials file is needed for this. This should be documented as part of the local development setup instructions.

**Comment by mike182uk** [comment]
Actually it looks like credentials are needed for a few different services: 

```
var github = require('./github.credentials');
var auth = require('./auth.credentials');
var stripe = require('./stripe.credentials');
var meetup = require('./meetup.credentials');
```

**Comment by PatrickHeneise** [comment]
Agreed, that was there in earlier version of the README. You need a file exporting this content:

```
{
    user: '<the acting github username>',
    repos: {
      planning: '<target user>/<target planning repo>',
      speakers: '<target user>/<target speakers repo>',
      gitevent: '<target user>/<target gitevent repo>'
    },
    secret: '<a random secret that you copy into all webhook settings as secret>',
    token: '<personal access token from https://github.com/settings/tokens>'
  }
```

**Comment by iancrowther** [comment]
@PatrickHeneise can you drop in an *.example.js

**Comment by PatrickHeneise** [comment]
https://gist.github.com/PatrickHeneise/9fa500564b1b809a0894 current barcelonajs config

**Comment by mike182uk** [comment]
Added in 3542e97acae642dc1d57df0b45700b122323141f
