### ISSUE TITLE
Moment construction deprecation warning

### ISSUE THREAD

**Issue by mike182uk** [gitevents/core#130]
When creating an event (via github issue) i am getting the following in the console:

```
gitevents-events received planning event +0ms
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (/Users/mike/Projects/OS/gitevents/core/node_modules/moment/moment.js:775:105)
    at configFromString (/Users/mike/Projects/OS/gitevents/core/node_modules/moment/moment.js:895:32)
    at configFromInput (/Users/mike/Projects/OS/gitevents/core/node_modules/moment/moment.js:1388:13)
    at prepareConfig (/Users/mike/Projects/OS/gitevents/core/node_modules/moment/moment.js:1371:13)
    at createFromConfig (/Users/mike/Projects/OS/gitevents/core/node_modules/moment/moment.js:1338:44)
    at createLocalOrUTC (/Users/mike/Projects/OS/gitevents/core/node_modules/moment/moment.js:1420:16)
    at Function.create_utc__createUTC [as utc] (/Users/mike/Projects/OS/gitevents/core/node_modules/moment/moment.js:64:16)
    at /Users/mike/Projects/OS/gitevents/core/lib/events.js:212:31
    at /Users/mike/Projects/OS/gitevents/core/node_modules/markdown-pa
```

related to https://github.com/moment/moment/issues/1407

**Comment by PatrickHeneise** [comment]
That's odd, since there's a format given https://github.com/gitevents/core/blob/master/lib/events.js#L212

**Comment by PatrickHeneise** [comment]
did you pass on the issue header with the start date?

https://github.com/GiteventsPlayground/planning/issues/new?title=Meetup&body=---%0Aaddress%3A%20C%2F%20Fontella%202%2C%2008001%2C%20Barcelona%0Adate%3A%2031.12.2099%0Aname%3A%20BarcelonaJS%0Avenue%3A%20Mobile%20World%20Centre%0A%0A---%0A%0A%23%23%20Checklist%0A*%20%5B%20%5D%20Registration%20-%20%0A*%20%5B%20%5D%20Website%20-%20%0A*%20%5B%20%5D%20Meetup.com%0A*%20%5B%20%5D%20Mailing%20List%20-%20%0A*%20%5B%20%5D%20Video%20%26%20YouTube%20-%20%0A*%20%5B%20%5D%20Twitter%20-%20%0A*%20%5B%20%5D%20Speakers%20-%20%0A*%20%5B%20%5D%20Sponsors%0A*%20%5B%20%5D%20Hot%20Issue%27s%20-%20%0A*%20%5B%20%5D%20Venue%20-%20%0A%0A%40BarcelonaJS%2Fbarcelonajs%20

this data is *required*

**Comment by mike182uk** [comment]
Ah, yep i had a misconfiguration of the data
